FAQ = {
    "What does this app do?": "This app helps you manage your tasks efficiently.",
    "How do I sign up?": "You can sign up by clicking the 'Sign Up' button on the homepage.",
    "What are the pricing plans?": "We offer three plans: Basic, Pro, and Enterprise.",
    "How do I contact support?": "You can contact support at support@example.com.",
    "Where can I find tutorials?": "You can find tutorials in the 'Help' section of the app.",
    
    "What is a rental NFT?": "A rental NFT allows users to temporarily access and use digital assets like music tracks without full ownership.",
    "How does the rental process work?": "Users can browse available music NFTs, select a track, and rent it for a specified period using smart contracts.",
    "Which blockchain is this platform built on?": "Our platform runs on Ethereum and Layer 2 solutions for lower transaction fees and faster processing.",
    "What happens when my rental period expires?": "Once your rental period ends, access to the NFT will be revoked automatically by the smart contract.",
    "Can I resell or transfer a rented NFT?": "No, rented NFTs are non-transferable and can only be used by the renter for the specified duration.",
    "What payment methods are accepted?": "We accept cryptocurrency payments in ETH, USDC, and other supported stablecoins.",
    "Do artists earn royalties on rented music?": "Yes, artists receive royalties every time their NFT is rented, ensuring continuous revenue from their work.",
    "Is there a free trial option?": "Some artists offer free trials for a limited time before requiring payment for rentals.",
    "Can I create and list my own music NFTs?": "Yes, artists can mint their own NFTs and list them for rental directly on our platform.",
    "How do I ensure my rented NFT is authentic?": "Every NFT on our platform is verified through blockchain records to ensure authenticity and ownership.",
    "What happens if my transaction fails?": "If your transaction fails, funds will not be deducted. You can try again or contact support for assistance.",
    "Is there a refund policy?": "Once an NFT is rented, refunds are generally not available. However, in case of technical issues, contact support.",
    "Can I use rented music NFTs for commercial purposes?": "Usage rights depend on the NFT’s terms. Some may allow personal use only, while others permit commercial use.",
    "How do I report unauthorized content?": "If you find any unauthorized or pirated content, please report it through our support center.",
    "What wallet do I need to use this platform?": "You can use MetaMask, WalletConnect, or any EVM-compatible wallet.",
    "Is my data secure?": "Yes, our platform leverages blockchain technology to ensure transparency and security.",
}