services:
  - type: web
    name: tunechat-backend
    runtime: python
    repo: https://github.com/Baah-Danso-Kenneth/TuneCycle
    branch: dev
    buildCommand: "cd chatbot_backend && ./build.sh"
    startCommand: "gunicorn chatbot_backend.wsgi:application --chdir chatbot_backend --bind 0.0.0.0:8000"
